### ISSUE TITLE
PyHEP 2024 "proceedings" - tag/release for Zenodo

### ISSUE THREAD

**Issue by eduardo-rodrigues** [ikrommyd/pyhep2024-coffea-dask#2]
This refers to https://indico.cern.ch/event/1384010/page/32779-proceedings:

Hello, could you prepare a tag/release of this repo you used for your PyHEP 2024 presentation so that I then mint a DOI on Zenodo, to be citable? Talks are trivial but for repositories a tag is a requirement for the minting.

You can see last year's example at https://zenodo.org/communities/pyhep2023/.

Let me know when done and I will take care of the rest. Advance thanks.

**Comment by ikrommyd** [comment]
Yup, I'll do it after the talks today :)

**Comment by ikrommyd** [comment]
@eduardo-rodrigues Done! Also for my zfit talk.
